### PR TITLE
pcsc-lite: update to 1.9.0

### PR DESCRIPTION
**Pull request by Lctrs**

### CODE REVIEW

**Comment by barthalion** [comment]
I assume it's backwards compatible?

**Comment by Lctrs** [comment]
@barthalion Can't guarantee it but from what I can see in the [diff](https://github.com/LudovicRousseau/PCSC/compare/1.8.26...pcsc-1.9.0), it should be.

**Comment by Lctrs** [comment]
I have updated 2 flatpaks (https://github.com/flathub/com.microsoft.Teams and https://github.com/flathub/com.axosoft.GitKraken) to this version several weeks ago without any problem though.

**Comment by barthalion** [comment]
I'll merge it for now and test when it lands in Firefox Beta.

**Pull request merged**
